# Generated by Django 4.0.6 on 2022-07-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_groups', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
