# Generated by Django 4.0.6 on 2022-07-24 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='name')),
                ('contents', ckeditor.fields.RichTextField(db_index=True, verbose_name='contents')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='thumbnails/', verbose_name='thumbnail')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('is_public', models.BooleanField(default=False, help_text='If set, news will be visible on the main site. Otherwise it will be visible only on the admin page.', verbose_name='is public')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, verbose_name='name')),
                ('other_authors', models.TextField(blank=True, db_index=True, default=None, help_text='One author per line', null=True, verbose_name='other authors')),
                ('year', models.IntegerField(db_index=True, verbose_name='year')),
                ('type', models.CharField(choices=[('MAGAZINE_ARTICLE', 'Magazine article'), ('CHAPTER', 'Article collection/chapter'), ('REPORT', 'Report'), ('BOOK', 'Book/monograph'), ('PATENT', 'Patent'), ('THESIS', 'Thesis')], db_index=True, max_length=32, verbose_name='publication type')),
                ('annotation', ckeditor.fields.RichTextField(verbose_name='annotation')),
                ('pages', models.CharField(blank=True, default=None, help_text='Format: x-y (from x to y)', max_length=32, null=True, verbose_name='pages')),
                ('volume', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='volume')),
                ('link', models.CharField(blank=True, default=None, help_text='Link to publication in doi.org', max_length=512, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, default=None, null=True, verbose_name='info')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='publisher_photos/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
