# Generated by Django 4.0.6 on 2022-07-07 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contents', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(default=None, null=True, upload_to='uploads/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
