# Generated by Django 4.0.6 on 2022-07-25 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_related_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='annotation',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
