# Generated by Django 4.0.6 on 2022-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='patr',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
