# Generated by Django 4.0.6 on 2022-07-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_author_patr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='NewsItem',
        ),
    ]
