# Generated by Django 4.0.6 on 2022-07-18 13:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_article_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('edition', models.TextField()),
                ('publication_date', models.DateField()),
                ('contents', ckeditor.fields.RichTextField()),
                ('volume', models.CharField(blank=True, default='', max_length=64)),
                ('no', models.PositiveIntegerField(default=None, help_text='№ of publication', null=True)),
                ('pages', models.CharField(blank=True, default='', help_text='Format: x-y (from x to y)', max_length=32)),
                ('doi_link', models.CharField(blank=True, default='', help_text='Link to publication in doi.org', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patr', models.CharField(blank=True, default='', max_length=128)),
                ('info', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, default='', upload_to='publisher_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='app.publisher'),
        ),
    ]
