# Generated by Django 4.0.6 on 2022-07-20 12:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_publication_publisher_delete_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='contents',
            field=ckeditor.fields.RichTextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(db_index=True, to='app.publisher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_link',
            field=models.CharField(blank=True, default=None, help_text='Link to publication in doi.org', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='no',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='№ of publication', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, default=None, help_text='Format: x-y (from x to y)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='patr',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='publisher_photos/'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='app.tag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='app.tag'),
        ),
    ]
