# Generated by Django 4.0.6 on 2022-07-23 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_newsitem_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Staff',
        ),
    ]
