# Generated by Django 4.0.6 on 2022-07-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_publisher_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-id', 'name'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If public, it will be visible on the main page. Otherwise it will be visible only on the admin page.'),
        ),
    ]
