# Generated by Django 4.0.6 on 2022-07-23 12:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_newsitem_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id', 'name'], 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='no',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
        migrations.AddField(
            model_name='publication',
            name='annotation',
            field=models.TextField(default='default', verbose_name='annotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.CharField(default='default', help_text='Link to publication in doi.org', max_length=512, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='staff_authors',
            field=models.ManyToManyField(db_index=True, to='app.staff', verbose_name='authors (staff)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(db_index=True, default=2000, verbose_name='year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='contents',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is archived'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If set, news will be visible on the main site. Otherwise it will be visible only on the admin page.', verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='app.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.JSONField(db_index=True, default=None, verbose_name='other authors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.TextField(db_index=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, default=None, help_text='Format: x-y (from x to y)', max_length=32, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='info',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='patr',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='publisher_photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='name'),
        ),
    ]
