# Generated by Django 4.0.6 on 2022-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_publication_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(db_index=True, verbose_name='other authors'),
        ),
    ]
