# Generated by Django 4.0.6 on 2022-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_publication_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, db_index=True, default=None, null=True, verbose_name='other authors'),
        ),
    ]
