# Generated by Django 4.0.6 on 2022-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_authors_publication_other_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='other_authors',
            field=models.TextField(blank=True, db_index=True, default=None, help_text='One author per line', null=True, verbose_name='other authors'),
        ),
    ]
