# Generated by Django 4.0.6 on 2022-07-23 14:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_publication_other_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='annotation',
            field=ckeditor.fields.RichTextField(verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, default=None, help_text='Link to publication in doi.org', max_length=512, null=True, verbose_name='link'),
        ),
    ]
