# Generated by Django 4.0.6 on 2022-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_publication_annotation_alter_publication_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('MAGAZINE_ARTICLE', 'Magazine article'), ('CHAPTER', 'Article collection/chapter'), ('REPORT', 'Report'), ('BOOK', 'Book/monograph'), ('PATENT', 'Patent'), ('THESIS', 'Thesis')], db_index=True, default='BOOK', max_length=32, verbose_name='publication type'),
            preserve_default=False,
        ),
    ]
