# Generated by Django 4.0.6 on 2022-07-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='volume'),
        ),
    ]
